### ISSUE TITLE
Evitar usar tipos primitivos nas classes de entidade

### ISSUE THREAD

**Issue by samluiz** [lucasrenu/escola#1]
Na classe pessoa e professor, observei que tipos primitivos foram utilizados em vez dos tipos por referência (wrapper classes) da seguinte forma:

`private int id`
`private double salario`

É boa prática e mais seguro utilizar wrapper classes, tipos que são ponteiros que apenas apontam para o seu endereço de memória alocado no heap que guarda seu valor:

`private Integer id`
`private Double salario`

A principal vantagem é que tipos por referência podem ter valor nulo, exatamente o que queremos na orientação a objetos. Tipos primitivos não podem ser nulos, precisam ser inicializados com algum valor (no caso de int = 0, double = 0.0, etc) para funcionar.

Um exemplo prático é se o banco de dados gerar automaticamente o id da entidade. Dessa forma, precisariamos instanciar o objeto passando um id null, para só na operação de inserir no banco receber o id gerado e fazer um setId(idDoBanco).

Em qualquer outro caso o ideal é usar tipos primitivos, pois são mais performáticos. Mas no caso de uma entidade, sempre usem tipos por referência, pois podem ser nulos e ficam alocados no heap, portanto é fácil de fazer outro ponteiro apontar para aquele valor no heap, sem precisar copiar o objeto.

[Se quiserem entender melhor.](https://pt.stackoverflow.com/a/530375)

Ótimo projeto, parabéns!

**Comment by lucasrenu** [comment]
Opa! Obrigado pela observação, não tinha pensado nisso.
Eu na hora de fazer a inserção no banco não estava passando o parâmetro do ID.
